export const SECTIONS = [
  { name: 'Save Our Pollinators', sort_order: 0 },
  { name: 'Indoors', sort_order: 1 },
  { name: 'Outdoors', sort_order: 2 },
];

export const PRODUCTS = [
  { section: 'Indoors', sort_order: 0, name: 'Wine Rack', price: 50, deposit_price: 25, delivery_price: 15, stripe_url: 'https://buy.stripe.com/8x27sK4Jo8zu9gO0cn6g80d', is_retail: true, is_featured: true, description: 'Elevate your wine collection with our handcrafted wine rack.', features: ['Holds up to 12 wine bottles', 'Built-in wine glass holder', 'Made from premium pine', 'Sturdy construction', 'Easy to assemble'], dimensions: '19" tall x 24" wide', delivery: 'Delivery available for $15', images: [{ src: '/wine-rack.jpg', alt: 'Handcrafted wine rack' }] },
  { section: 'Outdoors', sort_order: 0, name: 'Waterproof Patio Storage Bench', price: 300, deposit_price: 150, delivery_price: 150, stripe_url: 'https://buy.stripe.com/28E4gy3Fk5ni2Sq8IT6g801', is_retail: false, is_featured: false, description: 'Premium waterproof storage bench.', features: ['Fully waterproof construction', 'Dual-purpose design'], dimensions: '48" wide x 22" deep x 25.5" tall', delivery: 'Delivery available within Denver area for $150', images: [{ src: '/open-patio-storage-box.jpg', alt: 'Patio storage bench' }, { src: '/closed-patio-storage-box.jpg', alt: 'Closed bench' }] },
  { section: 'Outdoors', sort_order: 1, name: 'Backyard Tool Shed', price: 300, deposit_price: 125, delivery_price: 125, stripe_url: 'https://buy.stripe.com/4gM5kC4Jo02Y50ygbl6g803', is_retail: false, is_featured: false, description: 'Keep your tools dry and organized.', features: ['Fully enclosed', 'Barn-style doors'], dimensions: '36" wide x 18" deep x 48" tall', delivery: 'Delivery in Denver area for $125', images: [{ src: '/tool-shed.png', alt: 'Tool shed' }] },
  { section: 'Outdoors', sort_order: 2, name: 'Standard Planter Box', price: 60, deposit_price: 30, delivery_price: 15, stripe_url: 'https://buy.stripe.com/7sYeVcfo2eXS9gOgbl6g80e', is_retail: true, is_featured: false, description: 'Versatile planter for herbs and flowers.', features: ['Premium cedar', 'Built-in drainage'], dimensions: '24" x 12" x 12"', delivery: 'Delivery available for $15', images: [{ src: '/standard-planter-box.jpg', alt: 'Planter box' }] },
  { section: 'Outdoors', sort_order: 3, name: 'Garden Bench', price: 100, deposit_price: 50, delivery_price: 150, stripe_url: 'https://buy.stripe.com/28E5kC1xc7vqfFc2kv6g805', is_retail: true, is_featured: false, description: 'Handcrafted garden bench.', features: ['Pressure-treated lumber', 'Weather-resistant'], dimensions: '48" wide x 18" deep', delivery: 'Delivery in Denver area for $150', images: [{ src: '/2-by-4-garden-bench.jpg', alt: 'Garden bench' }] },
  { section: 'Outdoors', sort_order: 4, name: 'Quarter Cord Firewood Rack', price: 250, deposit_price: 100, delivery_price: 150, stripe_url: 'https://buy.stripe.com/dRm00i8ZE1728cK1gr6g80c', is_retail: true, is_featured: true, description: 'Firewood storage with galvanized roof.', features: ['Pressure-treated lumber', 'Galvanized tin roof'], dimensions: "2' x 4' x 5'", delivery: 'Delivery in Denver for $150', images: [{ src: '/quarter-cord.jpg', alt: 'Firewood rack' }] },
  { section: 'Outdoors', sort_order: 5, name: 'Half Cord Firewood Rack', price: 450, deposit_price: 200, delivery_price: 150, stripe_url: 'https://buy.stripe.com/7sY00iejYeXS9gO3oz6g807', is_retail: false, is_featured: false, description: 'Serious firewood storage.', features: ['Extra sturdy', 'Galvanized roof'], dimensions: "2' x 6' x 6'", delivery: 'Delivery in Denver for $150', images: [{ src: '/half-cord.jpg', alt: 'Half cord rack' }, { src: '/half-cord-2.jpg', alt: 'Half cord alternate' }] },
  { section: 'Outdoors', sort_order: 6, name: 'Full Cord Firewood Rack', price: 750, deposit_price: 200, delivery_price: 150, stripe_url: 'https://buy.stripe.com/5kQ8wOfo29Dy3Wugbl6g808', is_retail: false, is_featured: false, description: 'Largest firewood storage solution.', features: ['Full cord capacity', 'Heavy-duty'], dimensions: "4' x 4' x 8'", delivery: 'Delivery in Denver for $150', images: [{ src: '/full-cord.jpg', alt: 'Full cord rack' }] },
  { section: 'Outdoors', sort_order: 7, name: 'Utility Meter & Panel Cover Cabinet', price: 350, deposit_price: 200, delivery_price: 150, stripe_url: 'https://buy.stripe.com/aFafZg0t8eXSakScZ96g80a', is_retail: false, is_featured: false, description: 'Protect and conceal electrical meter.', features: ['Weather-resistant', 'Double doors'], dimensions: '36" x 20" x 54"', delivery: 'Delivery in Denver for $150', images: [{ src: '/utility-cover.jpg', alt: 'Utility cabinet' }] },
  { section: 'Indoors', sort_order: 1, name: 'River Resin Dining Table', price: 750, deposit_price: 300, delivery_price: 150, stripe_url: 'https://buy.stripe.com/7sYbJ0cbQ4je0Ki4sD6g809', is_retail: false, is_featured: false, description: 'Stunning resin dining or desk table.', features: ['Premium resin and wood', 'Unique design'], dimensions: '72" x 36" x 30"', delivery: 'Delivery in Denver for $150', images: [{ src: '/resin-table.jpg', alt: 'Resin table' }] },
  { section: 'Indoors', sort_order: 2, name: 'River Resin Side Table', price: 200, deposit_price: 100, delivery_price: 15, stripe_url: 'https://buy.stripe.com/aFa3cu4Jo4je1OmaR16g80b', is_retail: false, is_featured: false, description: 'Colorful side tables.', features: ['Multiple colors', 'Heavy-duty'], dimensions: '20" x 20" x 16"', delivery: 'Delivery for $15', images: [{ src: '/side-table-green.jpg', alt: 'Green side table' }, { src: '/side-table-blue.jpg', alt: 'Blue side table' }, { src: '/side-table-black.jpg', alt: 'Black side table' }] },
  { section: 'Save Our Pollinators', sort_order: 0, name: 'Beeswax Candle Set (2-pack)', price: 30, deposit_price: 15, delivery_price: 10, stripe_url: 'https://buy.stripe.com/3cI9AS8ZEaHC8cKcZ96g80f', is_retail: true, is_featured: true, description: 'Local beeswax candles.', features: ['100% pure beeswax', 'Hand-poured in Denver'], dimensions: 'Set: 1x 3"x4", 1x 2"x3"', delivery: 'Delivery for $10', images: [{ src: '/two-candle-bees-wax-set.png', alt: 'Beeswax candles' }, { src: '/two-candle-bees-wax-on-window.jpg', alt: 'Candles on sill' }] },
  { section: 'Save Our Pollinators', sort_order: 1, name: 'Organic Local Honey - 8 oz', price: 12, deposit_price: 12, delivery_price: 10, stripe_url: 'https://buy.stripe.com/5kQ14mb7MaHC1OmcZ96g80g', is_retail: true, is_featured: true, description: 'Pure organic local honey.', features: ['100% raw', 'Never processed'], dimensions: '8 oz jar', delivery: 'Delivery for $10', images: [{ src: '/kings-queen-honey-small-jar-white.jpg', alt: '8 oz honey' }] },
  { section: 'Save Our Pollinators', sort_order: 2, name: 'Organic Local Honey - 32 oz', price: 32, deposit_price: 32, delivery_price: 10, stripe_url: 'https://buy.stripe.com/7sYfZgdfUdTO8cK6AL6g80h', is_retail: true, is_featured: false, description: 'Full quart of local honey.', features: ['Raw organic', 'Mason jar'], dimensions: '32 oz jar', delivery: 'Delivery for $10', images: [{ src: '/kings-queen-jars-in-window.jpg', alt: '32 oz honey' }] },
  { section: 'Save Our Pollinators', sort_order: 3, name: 'Beeswaxed Pinecone Firestarters (4-Pack)', price: 12, deposit_price: 12, delivery_price: 10, stripe_url: 'https://buy.stripe.com/9B6cN46Rw8zu9gO2kv6g80i', is_retail: true, is_featured: false, description: 'Pinecone firestarters dipped in beeswax.', features: ['4-pack', '8–10 min burn each'], dimensions: '4-pack', delivery: 'Delivery for $10', images: [{ src: '/firestarters.jpg', alt: 'Firestarters' }] },
  { section: 'Save Our Pollinators', sort_order: 4, name: "Her Majesty's Bee Garden Kit", price: 12, deposit_price: 12, delivery_price: 10, stripe_url: 'https://buy.stripe.com/eVqdR8a3I6rm0KibV56g80j', is_retail: true, is_featured: false, description: 'Pollinator-friendly seed collection.', features: ['Annual and perennial', 'Easy to grow'], dimensions: 'Seed kit', delivery: 'Delivery for $10', images: [{ src: '/bee-garden-seed-kit.jpg', alt: 'Bee garden kit' }] },
];
